from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

REQUIRED_DIRS = [
    "ingest",
    "normalize",
    "evidence",
    "content_spec",
    "llm_router",
    "generation",
    "qa",
    "publish",
    "analytics",
    "commerce",
    "ops",
    "prompts",
    "tests",
    "docs",
]

CONFIG_TEMPLATE = """# AI Affiliate Automation settings
project_name: ai-affiliate-media
runtime_mode: deterministic_first
storage:
  db: sqlite:///./data/automation.db
  evidence_root: ./workspace/evidence
llm:
  enabled: true
  daily_budget_jpy: 5000
  weekly_budget_jpy: 25000
  call_policy:
    summarize: small
    synthesize: small
    generation: high_quality
    review: review
  deterministic_first_threshold: 0.75
channels:
  social:
    - x
    - tiktok
    - youtube_shorts
    - instagram_reels
  conversion:
    - seo_lp
    - newsletter
risk_controls:
  auto_dm: false
  auto_comment: false
  auto_follow_unfollow: false
  require_human_review_for_high_risk: true
"""

PROMPT_INDEX_TEMPLATE = """# Prompt inventory
# Keep business background and prompt templates separated.

business_background_file: docs/business_background.md
prompt_library_file: docs/prompt_library.md
required_checks:
  - no_hype_claims
  - no_fake_testimonials
  - route_to_owned_lp_before_affiliate
"""

README_TEMPLATE = """# AI Affiliate Automation Workspace

This workspace was generated by `python -m app.cli bootstrap-ai-affiliate`.

## Goal
Build and operate a deterministic-first media automation system where:
- backend operations are automated,
- high-risk publication decisions remain human-reviewed,
- affiliate and self-product routing are separated from social distribution.

## Next steps
1. Fill `business_background.md` with your validated strategy inputs.
2. Fill `prompt_library.md` with approved prompts.
3. Update `automation_config.yaml` budgets and risk limits.
4. Implement each module incrementally and add tests before production use.
"""

BACKGROUND_TEMPLATE = """# 事業背景 (編集用)

このファイルは「事業背景」専用です。プロンプト本文はここに混ぜないでください。

- ターゲット読者:
- 主商材(Hero):
- 収益の柱(Cash Cow):
- 集客商材(Traffic Magnet):
- 禁止運用:
- 90日の達成目標:
"""

PROMPT_LIBRARY_TEMPLATE = """# プロンプトライブラリ (編集用)

このファイルは「プロンプト定義」専用です。事業背景はここに混ぜないでください。

## STR-01
- 用途:
- 入力:
- 出力:

## CNT-01
- 用途:
- 入力:
- 出力:
"""

GUIDE_TEMPLATE = """# 実装状況と初期設定ガイド

## 1. 何をどこまで開発したか
- deterministic-first の雛形ディレクトリを作成
- 設定ファイル雛形 (`automation_config.yaml`) を追加
- 事業背景とプロンプトを分離して管理するための文書テンプレートを追加
- すぐ着手できるワークスペースREADMEを追加

## 2. 事前設定なしで動くか
最小限の雛形生成コマンドは **事前設定なしで実行可能** です。
ただし、実際の自動化運用（LLM接続、CMS連携、配信、分析）には次が必要です。

- APIキー/資格情報
- DB設定
- 媒体別ポリシーに沿った承認フロー
- 証拠キャプチャの実行環境

## 3. 初心者向けの進め方
1. `business_background.md` に事業の前提を箇条書きで記入
2. `prompt_library.md` に使うプロンプトだけを転記
3. `automation_config.yaml` で予算と禁止運用を設定
4. まず ingest/normalize から実装し、LLMは最後に接続
5. 公開は必ず QA を通し、リスク高は人手承認
"""


@dataclass(frozen=True)
class ScaffoldResult:
    root: Path
    created_dirs: list[str]
    created_files: list[str]


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def bootstrap_ai_affiliate_workspace(base_dir: Path) -> ScaffoldResult:
    root = base_dir / "ai_affiliate_automation"
    created_dirs: list[str] = []
    created_files: list[str] = []

    for rel in REQUIRED_DIRS:
        p = root / rel
        if not p.exists():
            p.mkdir(parents=True, exist_ok=True)
            created_dirs.append(str(p.relative_to(base_dir)))

    files = {
        root / "automation_config.yaml": CONFIG_TEMPLATE,
        root / "prompts" / "prompt_index.yaml": PROMPT_INDEX_TEMPLATE,
        root / "README.md": README_TEMPLATE,
        root / "docs" / "business_background.md": BACKGROUND_TEMPLATE,
        root / "docs" / "prompt_library.md": PROMPT_LIBRARY_TEMPLATE,
        root / "docs" / "implementation_guide.md": GUIDE_TEMPLATE,
    }

    for path, content in files.items():
        existed = path.exists()
        _write(path, content)
        if not existed:
            created_files.append(str(path.relative_to(base_dir)))

    return ScaffoldResult(root=root, created_dirs=created_dirs, created_files=created_files)
